<?php

/**
 * @file
 * outcomes.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function outcomes_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Data interactive',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '010b97ae-9bea-4f69-ad66-7906e879ef3e',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'mediums',
  );
  $terms[] = array(
    'name' => 'Organization uses story',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '0bfe4136-bf73-4923-8aa0-1b3735ba95d3',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'meso',
  );
  $terms[] = array(
    'name' => 'Industry response',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '120b6944-3a9a-490c-995f-952a159c4ff1',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'mediums',
  );
  $terms[] = array(
    'name' => 'Localization',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '20101dd2-6ffb-40f4-ab19-22d9fc9ee32e',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'media',
  );
  $terms[] = array(
    'name' => 'TV',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '2399b4a4-7755-4409-ac05-330d96d10e86',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'mediums',
  );
  $terms[] = array(
    'name' => 'Radio',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '243d0be0-c731-467f-93c8-c972bfe044e2',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'mediums',
  );
  $terms[] = array(
    'name' => 'Staff gives interview (or public appearance)',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '2587093f-e778-4923-94bc-4809c8222246',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'media',
  );
  $terms[] = array(
    'name' => 'Audio',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '2c7196d0-e371-4ed4-9821-4f58f33445f0',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'mediums',
  );
  $terms[] = array(
    'name' => 'Hearing',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '3c873162-e9b9-4aaf-8ffa-12643edc5aad',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'macro',
  );
  $terms[] = array(
    'name' => 'Action',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '4f84c387-168b-49e1-abb5-35211943f922',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'micro',
  );
  $terms[] = array(
    'name' => 'Video',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '5adc329b-08c8-419a-b55c-1680f6950423',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'mediums',
  );
  $terms[] = array(
    'name' => 'Government investigation',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '5b6c9f6d-7311-442f-94e8-1d38e879c006',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'macro',
  );
  $terms[] = array(
    'name' => 'Print',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '5bc4f502-ba5e-4d64-85d1-2744897f1a7b',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'mediums',
  );
  $terms[] = array(
    'name' => 'Institutional action (firing, reorganization, etc.)',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '6462928b-22f7-4671-b612-80f66120ad77',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'macro',
  );
  $terms[] = array(
    'name' => 'Mention / Citation',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '6b2b8699-8401-4af5-93aa-89e22740a4d4',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'media',
  );
  $terms[] = array(
    'name' => 'Text',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '6dc38436-a0f9-4b49-870d-55c813765152',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'mediums',
  );
  $terms[] = array(
    'name' => 'Animation',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '7286196e-c3ae-4662-9a0e-0c0411236cd0',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'mediums',
  );
  $terms[] = array(
    'name' => 'Policy change',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '73fc5633-c8d4-419e-bbb8-498b8184ab56',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'macro',
  );
  $terms[] = array(
    'name' => 'Full story',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '741b56e2-dc6e-4702-819d-e7868c6853ca',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'media',
  );
  $terms[] = array(
    'name' => 'Attitude change',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '7e00cef6-5179-4e75-a6ae-2aaa1f6c06cf',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'micro',
  );
  $terms[] = array(
    'name' => 'Public official refers to story',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '845ab7cd-4952-46cd-8749-9aac10bbebd9',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'meso',
  );
  $terms[] = array(
    'name' => 'Social network influencer share',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '955e11e9-30a5-4bab-8d00-bae20dd72a51',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'micro',
  );
  $terms[] = array(
    'name' => 'Story about organization',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '992ddae7-a9aa-4880-8fbe-af2359e3860b',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'media',
  );
  $terms[] = array(
    'name' => 'Image / Infographic',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '9b2118ce-ba60-4adb-afbd-c72a0594a7c2',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'mediums',
  );
  $terms[] = array(
    'name' => 'Award',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '9d1c5f73-89b1-4b70-a9d0-ed6cba243662',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'meso',
  );
  $terms[] = array(
    'name' => 'Data app',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'a4d482dd-5f53-4c04-9b77-1ba06fa6cd0c',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'mediums',
  );
  $terms[] = array(
    'name' => 'Increased awareness / knowledge',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'a94ee2f9-2b6b-478f-8839-2b5ce8fde444',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'micro',
  );
  $terms[] = array(
    'name' => 'Law passed',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'ab414722-c2ca-4817-8db8-b30146d0ac76',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'macro',
  );
  $terms[] = array(
    'name' => 'Law proposed',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'c807524c-bc68-4d64-a62e-5afc1eee4d46',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'macro',
  );
  $terms[] = array(
    'name' => 'Editorial',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'fd8f3eba-1085-45ee-8c6a-0d44acedb3f1',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'media',
  );
  $terms[] = array(
    'name' => 'Lawsuit filed',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'fecd5efd-e8f9-4ae5-b58e-2d513cf62bb6',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'meso',
  );
  return $terms;
}
